/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AppRole = IDL.Variant({
  'accountant' : IDL.Null,
  'admin' : IDL.Null,
  'sales' : IDL.Null,
  'inventoryManager' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BarcodeExportFormat = IDL.Variant({
  'pdf' : IDL.Null,
  'png' : IDL.Null,
});
export const BarcodeBatchExportRequest = IDL.Record({
  'productIds' : IDL.Vec(IDL.Nat),
  'exportType' : BarcodeExportFormat,
});
export const T = IDL.Variant({
  'paid' : IDL.Null,
  'sent' : IDL.Null,
  'overdue' : IDL.Null,
  'draft' : IDL.Null,
});
export const InvoiceExportFormat = IDL.Variant({
  'pdf' : IDL.Null,
  'excel' : IDL.Null,
});
export const Time = IDL.Int;
export const ReportDateRange = IDL.Record({
  'endDate' : Time,
  'startDate' : Time,
});
export const InvoiceFilter = IDL.Record({
  'paymentStatus' : IDL.Opt(T),
  'customerId' : IDL.Opt(IDL.Nat),
  'invoiceDateRange' : IDL.Opt(ReportDateRange),
  'searchQuery' : IDL.Opt(IDL.Text),
});
export const BarcodeExportRequest = IDL.Record({
  'exportType' : BarcodeExportFormat,
  'productId' : IDL.Nat,
});
export const UserApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'appRole' : AppRole,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'department' : IDL.Text,
});
export const UserAccount = IDL.Record({
  'id' : IDL.Principal,
  'approvalStatus' : UserApprovalStatus,
  'profile' : UserProfile,
});
export const AppBootstrapState = IDL.Record({
  'isApproved' : IDL.Bool,
  'isAdmin' : IDL.Bool,
  'userProfile' : IDL.Opt(UserProfile),
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'created' : Time,
  'modified' : Time,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const DataEntry = IDL.Record({
  'id' : IDL.Nat,
  'created' : Time,
  'modified' : Time,
  'entryId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'entityType' : IDL.Text,
  'amount' : IDL.Nat,
});
export const InventoryRecord = IDL.Record({
  'id' : IDL.Nat,
  'created' : Time,
  'modified' : Time,
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'batch' : IDL.Text,
  'supplierId' : IDL.Nat,
});
export const Invoice = IDL.Record({
  'tax' : IDL.Nat,
  'status' : T,
  'created' : Time,
  'total' : IDL.Nat,
  'productIds' : IDL.Vec(IDL.Nat),
  'stockAdjusted' : IDL.Bool,
  'dueDate' : IDL.Opt(Time),
  'invoiceId' : IDL.Nat,
  'productId' : IDL.Nat,
  'lastModified' : Time,
  'imageUrl' : IDL.Opt(IDL.Text),
  'pdfUrl' : IDL.Opt(IDL.Text),
  'paymentDate' : IDL.Opt(Time),
  'quantity' : IDL.Nat,
  'customerId' : IDL.Nat,
  'orderIds' : IDL.Vec(IDL.Nat),
  'price' : IDL.Nat,
  'inventoryIds' : IDL.Vec(IDL.Nat),
});
export const OrderRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'created' : Time,
  'modified' : Time,
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'customerId' : IDL.Nat,
  'totalPrice' : IDL.Nat,
});
export const InventoryStatus = IDL.Variant({
  'low' : IDL.Null,
  'inStock' : IDL.Null,
  'outOfStock' : IDL.Null,
});
export const Product = IDL.Record({
  'inventoryStatus' : InventoryStatus,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'rack' : IDL.Text,
  'size' : IDL.Text,
  'description' : IDL.Text,
  'productId' : IDL.Nat,
  'shelf' : IDL.Text,
  'barcode' : IDL.Text,
  'stockLevel' : IDL.Nat,
  'price' : IDL.Nat,
  'warehouse' : IDL.Text,
  'supplierId' : IDL.Opt(IDL.Nat),
  'images' : IDL.Vec(ExternalBlob),
});
export const InventoryLocation = IDL.Record({
  'rack' : IDL.Text,
  'shelf' : IDL.Text,
  'warehouse' : IDL.Text,
});
export const ProfitLossReport = IDL.Record({
  'reportDateRange' : ReportDateRange,
  'revenue' : IDL.Nat,
  'grossProfit' : IDL.Nat,
  'cogs' : IDL.Nat,
  'expenses' : IDL.Nat,
  'netProfit' : IDL.Nat,
});
export const Stats = IDL.Record({
  'totalOrders' : IDL.Nat,
  'totalInventory' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'totalCustomers' : IDL.Nat,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const Notification = IDL.Record({
  'title' : IDL.Text,
  'userId' : IDL.Principal,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Time,
  'notificationId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInventoryEntry' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addProductImage' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
  'addSecondaryAdminEmail' : IDL.Func([IDL.Text], [], []),
  'assignAppRole' : IDL.Func([IDL.Principal, AppRole], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'batchExportBarcodes' : IDL.Func(
      [BarcodeBatchExportRequest],
      [ExternalBlob],
      [],
    ),
  'clearAllInvoices' : IDL.Func([], [], []),
  'clearPreviousRejection' : IDL.Func([IDL.Principal], [], []),
  'createCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createDataEntry' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createInvoice' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, T],
      [IDL.Nat],
      [],
    ),
  'createNotification' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'deleteAllInventory' : IDL.Func([], [], []),
  'deleteAllOrders' : IDL.Func([], [], []),
  'deleteCustomer' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteNotification' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'exportInvoiceHistory' : IDL.Func(
      [
        InvoiceExportFormat,
        IDL.Opt(InvoiceFilter),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [ExternalBlob],
      [],
    ),
  'exportProductBarcode' : IDL.Func([BarcodeExportRequest], [ExternalBlob], []),
  'getAllUserAccounts' : IDL.Func([], [IDL.Vec(UserAccount)], ['query']),
  'getBootstrapState' : IDL.Func([], [AppBootstrapState], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
  'getDataEntry' : IDL.Func([IDL.Nat], [IDL.Opt(DataEntry)], ['query']),
  'getInventoryEntry' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(InventoryRecord)],
      ['query'],
    ),
  'getInventoryReportBarcodes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Invoice)], ['query']),
  'getInvoiceHistory' : IDL.Func(
      [IDL.Opt(InvoiceFilter), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(Invoice)],
      ['query'],
    ),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(OrderRecord)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductLocation' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(InventoryLocation)],
      ['query'],
    ),
  'getProfitLossReport' : IDL.Func([Time, Time], [ProfitLossReport], ['query']),
  'getSignatureForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSignature' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'isAccountant' : IDL.Func([], [IDL.Bool], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isInventoryManager' : IDL.Func([], [IDL.Bool], ['query']),
  'isPreviouslyRejected' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isSalesManager' : IDL.Func([], [IDL.Bool], ['query']),
  'isSuperAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], []),
  'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'listDataEntries' : IDL.Func([], [IDL.Vec(DataEntry)], ['query']),
  'listInventory' : IDL.Func([], [IDL.Vec(InventoryRecord)], ['query']),
  'listInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'listNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'listOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listSecondaryAdminEmails' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'processPreviouslyRejectedUser' : IDL.Func([IDL.Principal], [], []),
  'removeSecondaryAdminEmail' : IDL.Func([IDL.Text], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setProductLocation' : IDL.Func([IDL.Nat, InventoryLocation], [], []),
  'stockAdjustInvoice' : IDL.Func([IDL.Nat], [], []),
  'updateInvoiceDocumentUrls' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'uploadUserSignature' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AppRole = IDL.Variant({
    'accountant' : IDL.Null,
    'admin' : IDL.Null,
    'sales' : IDL.Null,
    'inventoryManager' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BarcodeExportFormat = IDL.Variant({
    'pdf' : IDL.Null,
    'png' : IDL.Null,
  });
  const BarcodeBatchExportRequest = IDL.Record({
    'productIds' : IDL.Vec(IDL.Nat),
    'exportType' : BarcodeExportFormat,
  });
  const T = IDL.Variant({
    'paid' : IDL.Null,
    'sent' : IDL.Null,
    'overdue' : IDL.Null,
    'draft' : IDL.Null,
  });
  const InvoiceExportFormat = IDL.Variant({
    'pdf' : IDL.Null,
    'excel' : IDL.Null,
  });
  const Time = IDL.Int;
  const ReportDateRange = IDL.Record({ 'endDate' : Time, 'startDate' : Time });
  const InvoiceFilter = IDL.Record({
    'paymentStatus' : IDL.Opt(T),
    'customerId' : IDL.Opt(IDL.Nat),
    'invoiceDateRange' : IDL.Opt(ReportDateRange),
    'searchQuery' : IDL.Opt(IDL.Text),
  });
  const BarcodeExportRequest = IDL.Record({
    'exportType' : BarcodeExportFormat,
    'productId' : IDL.Nat,
  });
  const UserApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'appRole' : AppRole,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'department' : IDL.Text,
  });
  const UserAccount = IDL.Record({
    'id' : IDL.Principal,
    'approvalStatus' : UserApprovalStatus,
    'profile' : UserProfile,
  });
  const AppBootstrapState = IDL.Record({
    'isApproved' : IDL.Bool,
    'isAdmin' : IDL.Bool,
    'userProfile' : IDL.Opt(UserProfile),
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'created' : Time,
    'modified' : Time,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DataEntry = IDL.Record({
    'id' : IDL.Nat,
    'created' : Time,
    'modified' : Time,
    'entryId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'entityType' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const InventoryRecord = IDL.Record({
    'id' : IDL.Nat,
    'created' : Time,
    'modified' : Time,
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'batch' : IDL.Text,
    'supplierId' : IDL.Nat,
  });
  const Invoice = IDL.Record({
    'tax' : IDL.Nat,
    'status' : T,
    'created' : Time,
    'total' : IDL.Nat,
    'productIds' : IDL.Vec(IDL.Nat),
    'stockAdjusted' : IDL.Bool,
    'dueDate' : IDL.Opt(Time),
    'invoiceId' : IDL.Nat,
    'productId' : IDL.Nat,
    'lastModified' : Time,
    'imageUrl' : IDL.Opt(IDL.Text),
    'pdfUrl' : IDL.Opt(IDL.Text),
    'paymentDate' : IDL.Opt(Time),
    'quantity' : IDL.Nat,
    'customerId' : IDL.Nat,
    'orderIds' : IDL.Vec(IDL.Nat),
    'price' : IDL.Nat,
    'inventoryIds' : IDL.Vec(IDL.Nat),
  });
  const OrderRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'created' : Time,
    'modified' : Time,
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'customerId' : IDL.Nat,
    'totalPrice' : IDL.Nat,
  });
  const InventoryStatus = IDL.Variant({
    'low' : IDL.Null,
    'inStock' : IDL.Null,
    'outOfStock' : IDL.Null,
  });
  const Product = IDL.Record({
    'inventoryStatus' : InventoryStatus,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'rack' : IDL.Text,
    'size' : IDL.Text,
    'description' : IDL.Text,
    'productId' : IDL.Nat,
    'shelf' : IDL.Text,
    'barcode' : IDL.Text,
    'stockLevel' : IDL.Nat,
    'price' : IDL.Nat,
    'warehouse' : IDL.Text,
    'supplierId' : IDL.Opt(IDL.Nat),
    'images' : IDL.Vec(ExternalBlob),
  });
  const InventoryLocation = IDL.Record({
    'rack' : IDL.Text,
    'shelf' : IDL.Text,
    'warehouse' : IDL.Text,
  });
  const ProfitLossReport = IDL.Record({
    'reportDateRange' : ReportDateRange,
    'revenue' : IDL.Nat,
    'grossProfit' : IDL.Nat,
    'cogs' : IDL.Nat,
    'expenses' : IDL.Nat,
    'netProfit' : IDL.Nat,
  });
  const Stats = IDL.Record({
    'totalOrders' : IDL.Nat,
    'totalInventory' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'totalCustomers' : IDL.Nat,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const Notification = IDL.Record({
    'title' : IDL.Text,
    'userId' : IDL.Principal,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Time,
    'notificationId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInventoryEntry' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addProductImage' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
    'addSecondaryAdminEmail' : IDL.Func([IDL.Text], [], []),
    'assignAppRole' : IDL.Func([IDL.Principal, AppRole], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'batchExportBarcodes' : IDL.Func(
        [BarcodeBatchExportRequest],
        [ExternalBlob],
        [],
      ),
    'clearAllInvoices' : IDL.Func([], [], []),
    'clearPreviousRejection' : IDL.Func([IDL.Principal], [], []),
    'createCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createDataEntry' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createInvoice' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, T],
        [IDL.Nat],
        [],
      ),
    'createNotification' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'deleteAllInventory' : IDL.Func([], [], []),
    'deleteAllOrders' : IDL.Func([], [], []),
    'deleteCustomer' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteNotification' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'exportInvoiceHistory' : IDL.Func(
        [
          InvoiceExportFormat,
          IDL.Opt(InvoiceFilter),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [ExternalBlob],
        [],
      ),
    'exportProductBarcode' : IDL.Func(
        [BarcodeExportRequest],
        [ExternalBlob],
        [],
      ),
    'getAllUserAccounts' : IDL.Func([], [IDL.Vec(UserAccount)], ['query']),
    'getBootstrapState' : IDL.Func([], [AppBootstrapState], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
    'getDataEntry' : IDL.Func([IDL.Nat], [IDL.Opt(DataEntry)], ['query']),
    'getInventoryEntry' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(InventoryRecord)],
        ['query'],
      ),
    'getInventoryReportBarcodes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Invoice)], ['query']),
    'getInvoiceHistory' : IDL.Func(
        [IDL.Opt(InvoiceFilter), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(Invoice)],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(OrderRecord)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductLocation' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(InventoryLocation)],
        ['query'],
      ),
    'getProfitLossReport' : IDL.Func(
        [Time, Time],
        [ProfitLossReport],
        ['query'],
      ),
    'getSignatureForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSignature' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'isAccountant' : IDL.Func([], [IDL.Bool], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isInventoryManager' : IDL.Func([], [IDL.Bool], ['query']),
    'isPreviouslyRejected' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isSalesManager' : IDL.Func([], [IDL.Bool], ['query']),
    'isSuperAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], []),
    'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'listDataEntries' : IDL.Func([], [IDL.Vec(DataEntry)], ['query']),
    'listInventory' : IDL.Func([], [IDL.Vec(InventoryRecord)], ['query']),
    'listInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'listNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'listOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listSecondaryAdminEmails' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'processPreviouslyRejectedUser' : IDL.Func([IDL.Principal], [], []),
    'removeSecondaryAdminEmail' : IDL.Func([IDL.Text], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setProductLocation' : IDL.Func([IDL.Nat, InventoryLocation], [], []),
    'stockAdjustInvoice' : IDL.Func([IDL.Nat], [], []),
    'updateInvoiceDocumentUrls' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'uploadUserSignature' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };