/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppBootstrapState {
  'isApproved' : boolean,
  'isAdmin' : boolean,
  'userProfile' : [] | [UserProfile],
}
export type AppRole = { 'accountant' : null } |
  { 'admin' : null } |
  { 'sales' : null } |
  { 'inventoryManager' : null };
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface BarcodeBatchExportRequest {
  'productIds' : Array<bigint>,
  'exportType' : BarcodeExportFormat,
}
export type BarcodeExportFormat = { 'pdf' : null } |
  { 'png' : null };
export interface BarcodeExportRequest {
  'exportType' : BarcodeExportFormat,
  'productId' : bigint,
}
export interface Customer {
  'id' : bigint,
  'created' : Time,
  'modified' : Time,
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface DataEntry {
  'id' : bigint,
  'created' : Time,
  'modified' : Time,
  'entryId' : bigint,
  'quantity' : bigint,
  'entityType' : string,
  'amount' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface InventoryLocation {
  'rack' : string,
  'shelf' : string,
  'warehouse' : string,
}
export interface InventoryRecord {
  'id' : bigint,
  'created' : Time,
  'modified' : Time,
  'productId' : bigint,
  'quantity' : bigint,
  'batch' : string,
  'supplierId' : bigint,
}
export type InventoryStatus = { 'low' : null } |
  { 'inStock' : null } |
  { 'outOfStock' : null };
export interface Invoice {
  'tax' : bigint,
  'status' : T,
  'created' : Time,
  'total' : bigint,
  'productIds' : Array<bigint>,
  'stockAdjusted' : boolean,
  'dueDate' : [] | [Time],
  'invoiceId' : bigint,
  'productId' : bigint,
  'lastModified' : Time,
  'imageUrl' : [] | [string],
  'pdfUrl' : [] | [string],
  'paymentDate' : [] | [Time],
  'quantity' : bigint,
  'customerId' : bigint,
  'orderIds' : Array<bigint>,
  'price' : bigint,
  'inventoryIds' : Array<bigint>,
}
export type InvoiceExportFormat = { 'pdf' : null } |
  { 'excel' : null };
export interface InvoiceFilter {
  'paymentStatus' : [] | [T],
  'customerId' : [] | [bigint],
  'invoiceDateRange' : [] | [ReportDateRange],
  'searchQuery' : [] | [string],
}
export interface Notification {
  'title' : string,
  'userId' : Principal,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : Time,
  'notificationId' : bigint,
}
export interface OrderRecord {
  'id' : bigint,
  'status' : string,
  'created' : Time,
  'modified' : Time,
  'productId' : bigint,
  'quantity' : bigint,
  'customerId' : bigint,
  'totalPrice' : bigint,
}
export interface Product {
  'inventoryStatus' : InventoryStatus,
  'name' : string,
  'color' : string,
  'rack' : string,
  'size' : string,
  'description' : string,
  'productId' : bigint,
  'shelf' : string,
  'barcode' : string,
  'stockLevel' : bigint,
  'price' : bigint,
  'warehouse' : string,
  'supplierId' : [] | [bigint],
  'images' : Array<ExternalBlob>,
}
export interface ProfitLossReport {
  'reportDateRange' : ReportDateRange,
  'revenue' : bigint,
  'grossProfit' : bigint,
  'cogs' : bigint,
  'expenses' : bigint,
  'netProfit' : bigint,
}
export interface ReportDateRange { 'endDate' : Time, 'startDate' : Time }
export interface Stats {
  'totalOrders' : bigint,
  'totalInventory' : bigint,
  'totalRevenue' : bigint,
  'totalCustomers' : bigint,
}
export type T = { 'paid' : null } |
  { 'sent' : null } |
  { 'overdue' : null } |
  { 'draft' : null };
export type Time = bigint;
export interface UserAccount {
  'id' : Principal,
  'approvalStatus' : UserApprovalStatus,
  'profile' : UserProfile,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface UserProfile {
  'appRole' : AppRole,
  'name' : string,
  'email' : string,
  'department' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInventoryEntry' : ActorMethod<[bigint, bigint, string, bigint], bigint>,
  'addProduct' : ActorMethod<
    [
      string,
      string,
      bigint,
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    bigint
  >,
  'addProductImage' : ActorMethod<[bigint, ExternalBlob], undefined>,
  'addSecondaryAdminEmail' : ActorMethod<[string], undefined>,
  'assignAppRole' : ActorMethod<[Principal, AppRole], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'batchExportBarcodes' : ActorMethod<
    [BarcodeBatchExportRequest],
    ExternalBlob
  >,
  'clearAllInvoices' : ActorMethod<[], undefined>,
  'clearPreviousRejection' : ActorMethod<[Principal], undefined>,
  'createCustomer' : ActorMethod<[string, string, string, string], bigint>,
  'createDataEntry' : ActorMethod<[string, bigint, bigint, bigint], bigint>,
  'createInvoice' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, bigint, T],
    bigint
  >,
  'createNotification' : ActorMethod<[Principal, string, string], bigint>,
  'createOrder' : ActorMethod<[bigint, bigint, bigint, string, bigint], bigint>,
  'deleteAllInventory' : ActorMethod<[], undefined>,
  'deleteAllOrders' : ActorMethod<[], undefined>,
  'deleteCustomer' : ActorMethod<[bigint], boolean>,
  'deleteNotification' : ActorMethod<[bigint], boolean>,
  'exportInvoiceHistory' : ActorMethod<
    [InvoiceExportFormat, [] | [InvoiceFilter], [] | [string], [] | [string]],
    ExternalBlob
  >,
  'exportProductBarcode' : ActorMethod<[BarcodeExportRequest], ExternalBlob>,
  'getAllUserAccounts' : ActorMethod<[], Array<UserAccount>>,
  'getBootstrapState' : ActorMethod<[], AppBootstrapState>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[bigint], [] | [Customer]>,
  'getDataEntry' : ActorMethod<[bigint], [] | [DataEntry]>,
  'getInventoryEntry' : ActorMethod<[bigint], [] | [InventoryRecord]>,
  'getInventoryReportBarcodes' : ActorMethod<[], Array<string>>,
  'getInvoice' : ActorMethod<[bigint], [] | [Invoice]>,
  'getInvoiceHistory' : ActorMethod<
    [[] | [InvoiceFilter], [] | [string], [] | [string]],
    Array<Invoice>
  >,
  'getOrder' : ActorMethod<[bigint], [] | [OrderRecord]>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductLocation' : ActorMethod<[bigint], [] | [InventoryLocation]>,
  'getProfitLossReport' : ActorMethod<[Time, Time], ProfitLossReport>,
  'getSignatureForUser' : ActorMethod<[Principal], [] | [ExternalBlob]>,
  'getStats' : ActorMethod<[], Stats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSignature' : ActorMethod<[], [] | [ExternalBlob]>,
  'isAccountant' : ActorMethod<[], boolean>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isInventoryManager' : ActorMethod<[], boolean>,
  'isPreviouslyRejected' : ActorMethod<[Principal], boolean>,
  'isSalesManager' : ActorMethod<[], boolean>,
  'isSuperAdmin' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listCustomers' : ActorMethod<[], Array<Customer>>,
  'listDataEntries' : ActorMethod<[], Array<DataEntry>>,
  'listInventory' : ActorMethod<[], Array<InventoryRecord>>,
  'listInvoices' : ActorMethod<[], Array<Invoice>>,
  'listNotifications' : ActorMethod<[], Array<Notification>>,
  'listOrders' : ActorMethod<[], Array<OrderRecord>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'listSecondaryAdminEmails' : ActorMethod<[], Array<string>>,
  'markNotificationAsRead' : ActorMethod<[bigint], boolean>,
  'processPreviouslyRejectedUser' : ActorMethod<[Principal], undefined>,
  'removeSecondaryAdminEmail' : ActorMethod<[string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setProductLocation' : ActorMethod<[bigint, InventoryLocation], undefined>,
  'stockAdjustInvoice' : ActorMethod<[bigint], undefined>,
  'updateInvoiceDocumentUrls' : ActorMethod<
    [bigint, [] | [string], [] | [string]],
    boolean
  >,
  'updateProduct' : ActorMethod<
    [
      bigint,
      string,
      string,
      bigint,
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'uploadUserSignature' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];