/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BarcodeExportRequest {
    exportType: BarcodeExportFormat;
    productId: bigint;
}
export interface Product {
    inventoryStatus: InventoryStatus;
    name: string;
    color: string;
    rack: string;
    size: string;
    description: string;
    productId: bigint;
    shelf: string;
    barcode: string;
    stockLevel: bigint;
    price: bigint;
    warehouse: string;
    supplierId?: bigint;
    images: Array<ExternalBlob>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Stats {
    totalOrders: bigint;
    totalInventory: bigint;
    totalRevenue: bigint;
    totalCustomers: bigint;
}
export interface ReportDateRange {
    endDate: Time;
    startDate: Time;
}
export interface ProfitLossReport {
    reportDateRange: ReportDateRange;
    revenue: bigint;
    grossProfit: bigint;
    cogs: bigint;
    expenses: bigint;
    netProfit: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DataEntry {
    id: bigint;
    created: Time;
    modified: Time;
    entryId: bigint;
    quantity: bigint;
    entityType: string;
    amount: bigint;
}
export interface BootstrapStatus {
    canisterStatus?: SystemStatus;
    backendAvailable: boolean;
    jsonSupport: boolean;
}
export interface AppBootstrapState {
    isApproved: boolean;
    isAdmin: boolean;
    userProfile?: UserProfile;
}
export interface InventoryRecord {
    id: bigint;
    created: Time;
    modified: Time;
    productId: bigint;
    quantity: bigint;
    batch: string;
    supplierId: bigint;
}
export interface InventoryLocation {
    rack: string;
    shelf: string;
    warehouse: string;
}
export interface BarcodeBatchExportRequest {
    productIds: Array<bigint>;
    exportType: BarcodeExportFormat;
}
export interface InvoiceFilter {
    paymentStatus?: T;
    customerId?: bigint;
    invoiceDateRange?: ReportDateRange;
    searchQuery?: string;
}
export interface OrderRecord {
    id: bigint;
    status: string;
    created: Time;
    modified: Time;
    productId: bigint;
    quantity: bigint;
    customerId: bigint;
    totalPrice: bigint;
}
export interface Invoice {
    tax: bigint;
    status: T;
    created: Time;
    total: bigint;
    productIds: Array<bigint>;
    stockAdjusted: boolean;
    dueDate?: Time;
    invoiceId: bigint;
    productId: bigint;
    lastModified: Time;
    imageUrl?: string;
    pdfUrl?: string;
    paymentDate?: Time;
    quantity: bigint;
    customerId: bigint;
    orderIds: Array<bigint>;
    price: bigint;
    inventoryIds: Array<bigint>;
}
export interface Customer {
    id: bigint;
    created: Time;
    modified: Time;
    name: string;
    email: string;
    address: string;
    phone: string;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface Notification {
    title: string;
    userId: Principal;
    isRead: boolean;
    message: string;
    timestamp: Time;
    notificationId: bigint;
}
export interface UserProfile {
    appRole: AppRole;
    name: string;
    email: string;
    department: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AppRole {
    accountant = "accountant",
    admin = "admin",
    sales = "sales",
    inventoryManager = "inventoryManager"
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum BarcodeExportFormat {
    pdf = "pdf",
    png = "png"
}
export enum InventoryStatus {
    low = "low",
    inStock = "inStock",
    outOfStock = "outOfStock"
}
export enum InvoiceExportFormat {
    pdf = "pdf",
    excel = "excel"
}
export enum SystemStatus {
    initialized = "initialized",
    unknown_ = "unknown"
}
export enum T {
    paid = "paid",
    sent = "sent",
    overdue = "overdue",
    draft = "draft"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addInventoryEntry(productId: bigint, quantity: bigint, batch: string, supplierId: bigint): Promise<bigint>;
    addProduct(name: string, description: string, price: bigint, stockLevel: bigint, warehouse: string, rack: string, shelf: string, size: string, color: string, barcode: string): Promise<bigint>;
    addProductImage(productId: bigint, blob: ExternalBlob): Promise<void>;
    addSecondaryAdminEmail(email: string): Promise<void>;
    approveUser(user: Principal): Promise<void>;
    assignAppRole(user: Principal, role: AppRole): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    batchExportBarcodes(arg0: BarcodeBatchExportRequest): Promise<ExternalBlob>;
    clearAllInvoices(): Promise<void>;
    clearPreviousRejection(user: Principal): Promise<void>;
    createCustomer(name: string, email: string, phone: string, address: string): Promise<bigint>;
    createDataEntry(entityType: string, entryId: bigint, amount: bigint, quantity: bigint): Promise<bigint>;
    createInvoice(customerId: bigint, productId: bigint, quantity: bigint, price: bigint, tax: bigint, total: bigint, status: T): Promise<bigint>;
    createNotification(targetUser: Principal, title: string, message: string): Promise<bigint>;
    createOrder(customerId: bigint, productId: bigint, quantity: bigint, status: string, totalPrice: bigint): Promise<bigint>;
    deleteAllInventory(): Promise<void>;
    deleteAllOrders(): Promise<void>;
    deleteCustomer(customerId: bigint): Promise<boolean>;
    deleteNotification(notificationId: bigint): Promise<boolean>;
    exportInvoiceHistory(arg0: InvoiceExportFormat, arg1: InvoiceFilter | null, arg2: string | null, arg3: string | null): Promise<ExternalBlob>;
    exportProductBarcode(arg0: BarcodeExportRequest): Promise<ExternalBlob>;
    getBootstrapState(): Promise<AppBootstrapState>;
    getBootstrapStatus(): Promise<BootstrapStatus>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomer(_customerId: bigint): Promise<Customer | null>;
    getDataEntry(dataEntryId: bigint): Promise<DataEntry | null>;
    getInventoryEntry(inventoryId: bigint): Promise<InventoryRecord | null>;
    getInventoryReportBarcodes(): Promise<Array<string>>;
    getInvoice(invoiceId: bigint): Promise<Invoice | null>;
    getInvoiceHistory(filter: InvoiceFilter | null, sortBy: string | null, sortOrder: string | null): Promise<Array<Invoice>>;
    getOrder(orderId: bigint): Promise<OrderRecord | null>;
    getPendingUsers(): Promise<Array<UserApprovalInfo>>;
    getProduct(productId: bigint): Promise<Product | null>;
    getProductLocation(productId: bigint): Promise<InventoryLocation | null>;
    getProfitLossReport(startDate: Time, endDate: Time): Promise<ProfitLossReport>;
    getSignatureForUser(user: Principal): Promise<ExternalBlob | null>;
    getStats(): Promise<Stats>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserSignature(): Promise<ExternalBlob | null>;
    isAccountant(): Promise<boolean>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    isInventoryManager(): Promise<boolean>;
    isPreviouslyRejected(user: Principal): Promise<boolean>;
    isSalesManager(): Promise<boolean>;
    isSuperAdmin(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    listCustomers(): Promise<Array<Customer>>;
    listDataEntries(): Promise<Array<DataEntry>>;
    listInventory(): Promise<Array<InventoryRecord>>;
    listInvoices(): Promise<Array<Invoice>>;
    listNotifications(): Promise<Array<Notification>>;
    listOrders(): Promise<Array<OrderRecord>>;
    listProducts(): Promise<Array<Product>>;
    listSecondaryAdminEmails(): Promise<Array<string>>;
    markNotificationAsRead(notificationId: bigint): Promise<boolean>;
    permanentlyRemoveUserAccount(targetUser: Principal): Promise<void>;
    processPreviouslyRejectedUser(user: Principal): Promise<void>;
    rejectUser(user: Principal): Promise<void>;
    removeSecondaryAdminEmail(email: string): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setProductLocation(productId: bigint, location: InventoryLocation): Promise<void>;
    stockAdjustInvoice(invoiceId: bigint): Promise<void>;
    updateInvoiceDocumentUrls(invoiceId: bigint, imageUrl: string | null, pdfUrl: string | null): Promise<boolean>;
    updateProduct(productId: bigint, name: string, description: string, price: bigint, stockLevel: bigint, warehouse: string, rack: string, shelf: string, size: string, color: string, barcode: string): Promise<void>;
    uploadUserSignature(signatureBlob: ExternalBlob): Promise<void>;
}
import type { AppBootstrapState as _AppBootstrapState, AppRole as _AppRole, ApprovalStatus as _ApprovalStatus, BarcodeBatchExportRequest as _BarcodeBatchExportRequest, BarcodeExportFormat as _BarcodeExportFormat, BarcodeExportRequest as _BarcodeExportRequest, BootstrapStatus as _BootstrapStatus, Customer as _Customer, DataEntry as _DataEntry, ExternalBlob as _ExternalBlob, InventoryLocation as _InventoryLocation, InventoryRecord as _InventoryRecord, InventoryStatus as _InventoryStatus, Invoice as _Invoice, InvoiceExportFormat as _InvoiceExportFormat, InvoiceFilter as _InvoiceFilter, OrderRecord as _OrderRecord, Product as _Product, ReportDateRange as _ReportDateRange, SystemStatus as _SystemStatus, T as _T, Time as _Time, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addInventoryEntry(arg0: bigint, arg1: bigint, arg2: string, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addInventoryEntry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInventoryEntry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addProduct(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async addProductImage(arg0: bigint, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProductImage(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProductImage(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addSecondaryAdminEmail(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSecondaryAdminEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSecondaryAdminEmail(arg0);
            return result;
        }
    }
    async approveUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveUser(arg0);
            return result;
        }
    }
    async assignAppRole(arg0: Principal, arg1: AppRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignAppRole(arg0, to_candid_AppRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignAppRole(arg0, to_candid_AppRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async batchExportBarcodes(arg0: BarcodeBatchExportRequest): Promise<ExternalBlob> {
        if (this.processError) {
            try {
                const result = await this.actor.batchExportBarcodes(to_candid_BarcodeBatchExportRequest_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ExternalBlob_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchExportBarcodes(to_candid_BarcodeBatchExportRequest_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ExternalBlob_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearAllInvoices(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllInvoices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllInvoices();
            return result;
        }
    }
    async clearPreviousRejection(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearPreviousRejection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearPreviousRejection(arg0);
            return result;
        }
    }
    async createCustomer(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomer(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomer(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createDataEntry(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDataEntry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDataEntry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createInvoice(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: T): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_T_n18(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_T_n18(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async createNotification(arg0: Principal, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotification(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotification(arg0, arg1, arg2);
            return result;
        }
    }
    async createOrder(arg0: bigint, arg1: bigint, arg2: bigint, arg3: string, arg4: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deleteAllInventory(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllInventory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllInventory();
            return result;
        }
    }
    async deleteAllOrders(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllOrders();
            return result;
        }
    }
    async deleteCustomer(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteNotification(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotification(arg0);
            return result;
        }
    }
    async exportInvoiceHistory(arg0: InvoiceExportFormat, arg1: InvoiceFilter | null, arg2: string | null, arg3: string | null): Promise<ExternalBlob> {
        if (this.processError) {
            try {
                const result = await this.actor.exportInvoiceHistory(to_candid_InvoiceExportFormat_n20(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg3));
                return from_candid_ExternalBlob_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportInvoiceHistory(to_candid_InvoiceExportFormat_n20(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg3));
            return from_candid_ExternalBlob_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async exportProductBarcode(arg0: BarcodeExportRequest): Promise<ExternalBlob> {
        if (this.processError) {
            try {
                const result = await this.actor.exportProductBarcode(to_candid_BarcodeExportRequest_n26(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ExternalBlob_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportProductBarcode(to_candid_BarcodeExportRequest_n26(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ExternalBlob_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBootstrapState(): Promise<AppBootstrapState> {
        if (this.processError) {
            try {
                const result = await this.actor.getBootstrapState();
                return from_candid_AppBootstrapState_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBootstrapState();
            return from_candid_AppBootstrapState_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBootstrapStatus(): Promise<BootstrapStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getBootstrapStatus();
                return from_candid_BootstrapStatus_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBootstrapStatus();
            return from_candid_BootstrapStatus_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: bigint): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDataEntry(arg0: bigint): Promise<DataEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDataEntry(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDataEntry(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInventoryEntry(arg0: bigint): Promise<InventoryRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryEntry(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryEntry(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInventoryReportBarcodes(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryReportBarcodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryReportBarcodes();
            return result;
        }
    }
    async getInvoice(arg0: bigint): Promise<Invoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoiceHistory(arg0: InvoiceFilter | null, arg1: string | null, arg2: string | null): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoiceHistory(to_candid_opt_n22(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoiceHistory(to_candid_opt_n22(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: bigint): Promise<OrderRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingUsers(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingUsers();
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingUsers();
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: bigint): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductLocation(arg0: bigint): Promise<InventoryLocation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductLocation(arg0);
                return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductLocation(arg0);
            return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfitLossReport(arg0: Time, arg1: Time): Promise<ProfitLossReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfitLossReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfitLossReport(arg0, arg1);
            return result;
        }
    }
    async getSignatureForUser(arg0: Principal): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSignatureForUser(arg0);
                return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSignatureForUser(arg0);
            return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSignature(): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSignature();
                return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSignature();
            return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAccountant(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAccountant();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAccountant();
            return result;
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async isInventoryManager(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isInventoryManager();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isInventoryManager();
            return result;
        }
    }
    async isPreviouslyRejected(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isPreviouslyRejected(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isPreviouslyRejected(arg0);
            return result;
        }
    }
    async isSalesManager(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isSalesManager();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isSalesManager();
            return result;
        }
    }
    async isSuperAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isSuperAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isSuperAdmin();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCustomers();
            return result;
        }
    }
    async listDataEntries(): Promise<Array<DataEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDataEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDataEntries();
            return result;
        }
    }
    async listInventory(): Promise<Array<InventoryRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInventory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInventory();
            return result;
        }
    }
    async listInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInvoices();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInvoices();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async listNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNotifications();
            return result;
        }
    }
    async listOrders(): Promise<Array<OrderRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOrders();
            return result;
        }
    }
    async listProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts();
                return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts();
            return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSecondaryAdminEmails(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSecondaryAdminEmails();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSecondaryAdminEmails();
            return result;
        }
    }
    async markNotificationAsRead(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async permanentlyRemoveUserAccount(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.permanentlyRemoveUserAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.permanentlyRemoveUserAccount(arg0);
            return result;
        }
    }
    async processPreviouslyRejectedUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.processPreviouslyRejectedUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processPreviouslyRejectedUser(arg0);
            return result;
        }
    }
    async rejectUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectUser(arg0);
            return result;
        }
    }
    async removeSecondaryAdminEmail(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeSecondaryAdminEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeSecondaryAdminEmail(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n68(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n68(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n70(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n70(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setProductLocation(arg0: bigint, arg1: InventoryLocation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProductLocation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProductLocation(arg0, arg1);
            return result;
        }
    }
    async stockAdjustInvoice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.stockAdjustInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.stockAdjustInvoice(arg0);
            return result;
        }
    }
    async updateInvoiceDocumentUrls(arg0: bigint, arg1: string | null, arg2: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoiceDocumentUrls(arg0, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoiceDocumentUrls(arg0, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateProduct(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string, arg10: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            return result;
        }
    }
    async uploadUserSignature(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadUserSignature(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadUserSignature(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AppBootstrapState_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppBootstrapState): AppBootstrapState {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_AppRole_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppRole): AppRole {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function from_candid_BootstrapStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BootstrapStatus): BootstrapStatus {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_InventoryStatus_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryStatus): InventoryStatus {
    return from_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function from_candid_Invoice_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n61(_uploadFile, _downloadFile, value);
}
function from_candid_SystemStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SystemStatus): SystemStatus {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_T_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T): T {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SystemStatus]): SystemStatus | null {
    return value.length === 0 ? null : from_candid_SystemStatus_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DataEntry]): DataEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InventoryRecord]): InventoryRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Invoice]): Invoice | null {
    return value.length === 0 ? null : from_candid_Invoice_n46(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OrderRecord]): OrderRecord | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Promise<Product | null> {
    return value.length === 0 ? null : await from_candid_Product_n60(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InventoryLocation]): InventoryLocation | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isApproved: boolean;
    isAdmin: boolean;
    userProfile: [] | [_UserProfile];
}): {
    isApproved: boolean;
    isAdmin: boolean;
    userProfile?: UserProfile;
} {
    return {
        isApproved: value.isApproved,
        isAdmin: value.isAdmin,
        userProfile: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.userProfile))
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    appRole: _AppRole;
    name: string;
    email: string;
    department: string;
}): {
    appRole: AppRole;
    name: string;
    email: string;
    department: string;
} {
    return {
        appRole: from_candid_AppRole_n33(_uploadFile, _downloadFile, value.appRole),
        name: value.name,
        email: value.email,
        department: value.department
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    canisterStatus: [] | [_SystemStatus];
    backendAvailable: boolean;
    jsonSupport: boolean;
}): {
    canisterStatus?: SystemStatus;
    backendAvailable: boolean;
    jsonSupport: boolean;
} {
    return {
        canisterStatus: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.canisterStatus)),
        backendAvailable: value.backendAvailable,
        jsonSupport: value.jsonSupport
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tax: bigint;
    status: _T;
    created: _Time;
    total: bigint;
    productIds: Array<bigint>;
    stockAdjusted: boolean;
    dueDate: [] | [_Time];
    invoiceId: bigint;
    productId: bigint;
    lastModified: _Time;
    imageUrl: [] | [string];
    pdfUrl: [] | [string];
    paymentDate: [] | [_Time];
    quantity: bigint;
    customerId: bigint;
    orderIds: Array<bigint>;
    price: bigint;
    inventoryIds: Array<bigint>;
}): {
    tax: bigint;
    status: T;
    created: Time;
    total: bigint;
    productIds: Array<bigint>;
    stockAdjusted: boolean;
    dueDate?: Time;
    invoiceId: bigint;
    productId: bigint;
    lastModified: Time;
    imageUrl?: string;
    pdfUrl?: string;
    paymentDate?: Time;
    quantity: bigint;
    customerId: bigint;
    orderIds: Array<bigint>;
    price: bigint;
    inventoryIds: Array<bigint>;
} {
    return {
        tax: value.tax,
        status: from_candid_T_n48(_uploadFile, _downloadFile, value.status),
        created: value.created,
        total: value.total,
        productIds: value.productIds,
        stockAdjusted: value.stockAdjusted,
        dueDate: record_opt_to_undefined(from_candid_opt_n50(_uploadFile, _downloadFile, value.dueDate)),
        invoiceId: value.invoiceId,
        productId: value.productId,
        lastModified: value.lastModified,
        imageUrl: record_opt_to_undefined(from_candid_opt_n51(_uploadFile, _downloadFile, value.imageUrl)),
        pdfUrl: record_opt_to_undefined(from_candid_opt_n51(_uploadFile, _downloadFile, value.pdfUrl)),
        paymentDate: record_opt_to_undefined(from_candid_opt_n50(_uploadFile, _downloadFile, value.paymentDate)),
        quantity: value.quantity,
        customerId: value.customerId,
        orderIds: value.orderIds,
        price: value.price,
        inventoryIds: value.inventoryIds
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n57(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
async function from_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inventoryStatus: _InventoryStatus;
    name: string;
    color: string;
    rack: string;
    size: string;
    description: string;
    productId: bigint;
    shelf: string;
    barcode: string;
    stockLevel: bigint;
    price: bigint;
    warehouse: string;
    supplierId: [] | [bigint];
    images: Array<_ExternalBlob>;
}): Promise<{
    inventoryStatus: InventoryStatus;
    name: string;
    color: string;
    rack: string;
    size: string;
    description: string;
    productId: bigint;
    shelf: string;
    barcode: string;
    stockLevel: bigint;
    price: bigint;
    warehouse: string;
    supplierId?: bigint;
    images: Array<ExternalBlob>;
}> {
    return {
        inventoryStatus: from_candid_InventoryStatus_n62(_uploadFile, _downloadFile, value.inventoryStatus),
        name: value.name,
        color: value.color,
        rack: value.rack,
        size: value.size,
        description: value.description,
        productId: value.productId,
        shelf: value.shelf,
        barcode: value.barcode,
        stockLevel: value.stockLevel,
        price: value.price,
        warehouse: value.warehouse,
        supplierId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.supplierId)),
        images: await from_candid_vec_n64(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    accountant: null;
} | {
    admin: null;
} | {
    sales: null;
} | {
    inventoryManager: null;
}): AppRole {
    return "accountant" in value ? AppRole.accountant : "admin" in value ? AppRole.admin : "sales" in value ? AppRole.sales : "inventoryManager" in value ? AppRole.inventoryManager : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    initialized: null;
} | {
    unknown: null;
}): SystemStatus {
    return "initialized" in value ? SystemStatus.initialized : "unknown" in value ? SystemStatus.unknown : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paid: null;
} | {
    sent: null;
} | {
    overdue: null;
} | {
    draft: null;
}): T {
    return "paid" in value ? T.paid : "sent" in value ? T.sent : "overdue" in value ? T.overdue : "draft" in value ? T.draft : value;
}
function from_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    inStock: null;
} | {
    outOfStock: null;
}): InventoryStatus {
    return "low" in value ? InventoryStatus.low : "inStock" in value ? InventoryStatus.inStock : "outOfStock" in value ? InventoryStatus.outOfStock : value;
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n55(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n17(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n60(_uploadFile, _downloadFile, x)));
}
function to_candid_AppRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): _AppRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_ApprovalStatus_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n71(_uploadFile, _downloadFile, value);
}
function to_candid_BarcodeBatchExportRequest_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BarcodeBatchExportRequest): _BarcodeBatchExportRequest {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_BarcodeExportFormat_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BarcodeExportFormat): _BarcodeExportFormat {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_BarcodeExportRequest_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BarcodeExportRequest): _BarcodeExportRequest {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_InvoiceExportFormat_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceExportFormat): _InvoiceExportFormat {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_InvoiceFilter_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceFilter): _InvoiceFilter {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_T_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T): _T {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n69(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceFilter | null): [] | [_InvoiceFilter] {
    return value === null ? candid_none() : candid_some(to_candid_InvoiceFilter_n23(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    productIds: Array<bigint>;
    exportType: BarcodeExportFormat;
}): {
    productIds: Array<bigint>;
    exportType: _BarcodeExportFormat;
} {
    return {
        productIds: value.productIds,
        exportType: to_candid_BarcodeExportFormat_n15(_uploadFile, _downloadFile, value.exportType)
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentStatus?: T;
    customerId?: bigint;
    invoiceDateRange?: ReportDateRange;
    searchQuery?: string;
}): {
    paymentStatus: [] | [_T];
    customerId: [] | [bigint];
    invoiceDateRange: [] | [_ReportDateRange];
    searchQuery: [] | [string];
} {
    return {
        paymentStatus: value.paymentStatus ? candid_some(to_candid_T_n18(_uploadFile, _downloadFile, value.paymentStatus)) : candid_none(),
        customerId: value.customerId ? candid_some(value.customerId) : candid_none(),
        invoiceDateRange: value.invoiceDateRange ? candid_some(value.invoiceDateRange) : candid_none(),
        searchQuery: value.searchQuery ? candid_some(value.searchQuery) : candid_none()
    };
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    exportType: BarcodeExportFormat;
    productId: bigint;
}): {
    exportType: _BarcodeExportFormat;
    productId: bigint;
} {
    return {
        exportType: to_candid_BarcodeExportFormat_n15(_uploadFile, _downloadFile, value.exportType),
        productId: value.productId
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    appRole: AppRole;
    name: string;
    email: string;
    department: string;
}): {
    appRole: _AppRole;
    name: string;
    email: string;
    department: string;
} {
    return {
        appRole: to_candid_AppRole_n9(_uploadFile, _downloadFile, value.appRole),
        name: value.name,
        email: value.email,
        department: value.department
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): {
    accountant: null;
} | {
    admin: null;
} | {
    sales: null;
} | {
    inventoryManager: null;
} {
    return value == AppRole.accountant ? {
        accountant: null
    } : value == AppRole.admin ? {
        admin: null
    } : value == AppRole.sales ? {
        sales: null
    } : value == AppRole.inventoryManager ? {
        inventoryManager: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BarcodeExportFormat): {
    pdf: null;
} | {
    png: null;
} {
    return value == BarcodeExportFormat.pdf ? {
        pdf: null
    } : value == BarcodeExportFormat.png ? {
        png: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T): {
    paid: null;
} | {
    sent: null;
} | {
    overdue: null;
} | {
    draft: null;
} {
    return value == T.paid ? {
        paid: null
    } : value == T.sent ? {
        sent: null
    } : value == T.overdue ? {
        overdue: null
    } : value == T.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceExportFormat): {
    pdf: null;
} | {
    excel: null;
} {
    return value == InvoiceExportFormat.pdf ? {
        pdf: null
    } : value == InvoiceExportFormat.excel ? {
        excel: null
    } : value;
}
function to_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
